### ISSUE TITLE
RAIN ai system errors

### ISSUE THREAD

**Issue by Mechasparrow** [IGDAStl/gateway3dwest#4]
Rain asset is missing?

**Comment by zfalconer** [comment]
That's... strange. Try deleting the rain folder then reimporting from the app store (its free)

--- Original Message ---

**Comment by zfalconer** [comment]
*asset store

**Comment by Mechasparrow** [comment]
Alright Ill try that

**Comment by Mechasparrow** [comment]
K got it fixed. I installed the asset and I reopened the project just to let you know :)
